version: "3"
services:
  server:
    build: ./
    ports:
      - "8081:8080"
    links:
      - redis
    environment:
      PORT: 8080
      REDIS_URL: "redis://redis:6379"
    env_file:
      - .env
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
