version: '3.7'
services:
  frontend:
    build: frontend
    ports:
      - 80:80
  backend-rest:
    build: 
      context: backend-rest
      args:
        BACKEND_INDEX_HOST: backend-index
    depends_on:
      - "backend-index"
    command: ["./wait-for-it.sh", "backend-index:5602", "--", "python", "app.py"]
    ports:
      - 5601:5601
  backend-index:
    build: backend-index
    ports:
      - 5602:5602