version: "3"

services:
  chroma:
    build:
      context: tools/chroma
    volumes:
      - ./tools/chroma:/chroma
      - index_data:/index_data
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config log_config.yml
    environment:
      - CHROMA_DB_IMPL=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    ports:
      - ${CHROMA_PORT}:8000
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:22.9-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    volumes:
      - clickhouse_data:/bitnami/clickhouse
      - backups:/backups
      - ./config/backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
      - ./config/chroma_users.xml:/etc/clickhouse-server/users.d/chroma.xml

  motorhead:
    build: tools/motorhead
    ports:
      - "${MOTORHEAD_PORT}:8080"
    links:
      - redis
    environment:
      PORT: 8080
      REDIS_URL: "redis://redis:6379"
  redis:
    image: redis:latest

  lighthouse:
    build: tools/lighthouse
    ports:
      - ${LIGHTHOUSE_PORT}:80

  docgpt-db:
    image: postgres:14.1
    environment:
      - POSTGRES_HOST=${DOCGPT_DB_HOST}
      - POSTGRES_DB=${DOCGPT_DB_NAME}
      - POSTGRES_USER=${DOCGPT_DB_USER}
      - POSTGRES_PASSWORD=${DOCGPT_DB_PASSWORD}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - docgpt-db
    ports:
      - ${DOCGPT_ADMINER_PORT}:8080

  frontend:
    build: frontend
    env_file:
      - .env
    ports:
      - "80:80"
  backend:
    build: backend
    environment:
      - DOCGPT_DB_HOST=${DOCGPT_DB_HOST}
      - DOCGPT_DB_PORT=${DOCGPT_DB_PORT}
      - DOCGPT_DB_NAME=${DOCGPT_DB_NAME}
      - DOCGPT_DB_USER=${DOCGPT_DB_USER}
      - DOCGPT_DB_PASSWORD=${DOCGPT_DB_PASSWORD}
      - MOTORHEAD_PORT=${MOTORHEAD_PORT}
      - MOTORHEAD_HOST=${MOTORHEAD_HOST}
      - CHROMA_HOST=${CHROMA_HOST}
      - CHROMA_PORT=${CHROMA_PORT}
      - LIGHTHOUSE_HOST=${LIGHTHOUSE_HOST}
      - LIGHTHOUSE_PORT=${LIGHTHOUSE_PORT}
    ports:
      - "3000:3000"
volumes:
  clickhouse_data:
  index_data:
  backups:
