version: "3"

services:
  docgpt-db:
    image: postgres:14.1
    environment:
      - POSTGRES_DB=${DOCGPT_DB_NAME}
      - POSTGRES_USER=${DOCGPT_DB_USER}
      - POSTGRES_PASSWORD=${DOCGPT_DB_PASSWORD}
    ports:
      - ${DOCGPT_DB_PORT}:5432
  adminer:
    image: adminer
    restart: always
    depends_on:
      - docgpt-db
    ports:
      - ${DOCGPT_ADMINER_PORT}:8080
  chroma:
    build:
      context: tools/chroma
    volumes:
      - ./tools/chroma:/chroma
      - index_data:/index_data
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config log_config.yml
    environment:
      - CHROMA_DB_IMPL=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=${CHROMA_DB_HTTP_PORT}
    ports:
      - ${CHROMA_SERVER_PORT}:8000
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:22.9-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    ports:
      - "${CHROMA_DB_HTTP_PORT}:8123"
      - "${CHROMA_DB_TCP_PORT}:9000"
    volumes:
      - clickhouse_data:/bitnami/clickhouse
      - backups:/backups
      - ./config/backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
      - ./config/chroma_users.xml:/etc/clickhouse-server/users.d/chroma.xml
  langchain-frontend:
    image: notlangchain/langchainplus-frontend:latest
    ports:
      - ${LANGCHAIN_FRONT_PORT}:4173
    environment:
      - BACKEND_URL=http://langchain-backend:8000
      - PUBLIC_BASE_URL=http://localhost:8000
      - PUBLIC_DEV_MODE=true
    depends_on:
      - langchain-backend
  langchain-backend:
    container_name: langchainplus_back
    image: notlangchain/langchainplus:latest
    environment:
      - PORT=8000
      - LANGCHAIN_ENV=local
    ports:
      - ${LANGCHAIN_BACK_PORT}:8000
    depends_on:
      - langchain-db
  langchain-db:
    container_name: langchainplus_db
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - ${LANGCHAIN_DB_PORT}:5432
  lighthouse:
    build: tools/lighthouse
    ports:
      - ${LIGHTHOUSE_PORT}:80
  motorhead:
    build: tools/motorhead
    ports:
      - "${MOTORHEAD_SERVER_PORT}:8080"
    links:
      - redis
    environment:
      PORT: 8080
      REDIS_URL: "redis://redis:6379"
  redis:
    image: redis:latest
    ports:
      - "${MOTORHEAD_REDIS_PORT}:6379"
  frontend:
    build: frontend
    env_file:
      - .env
    ports:
      - "80:80"
  backend:
    build: backend
    ports:
      - "3000:3000"
volumes:
  clickhouse_data:
  index_data:
  backups:
