version: "3"

services:
  langchain-frontend:
    container_name: langchainplus_front
    image: notlangchain/langchainplus-frontend:latest
    ports:
      - ${LANGCHAIN_FRONT_PORT}:4173
    environment:
      - BACKEND_URL=http://langchain-backend:8000
      - PUBLIC_BASE_URL=http://localhost:8000
      - PUBLIC_DEV_MODE=true
    depends_on:
      - langchain-backend
  langchain-backend:
    container_name: langchainplus_back
    image: notlangchain/langchainplus:latest
    environment:
      - PORT=8000
      - LANGCHAIN_ENV=local
    ports:
      - ${LANGCHAIN_BACK_PORT}:8000
    depends_on:
      - langchain-db
  langchain-db:
    container_name: langchainplus_db
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - ${LANGCHAIN_DB_PORT}:5432
