version: "3"
services:
  server:
    build: ./
    ports:
      - "${MOTORHEAD_SERVER_PORT}:8080"
    links:
      - redis
    environment:
      PORT: 8080
      REDIS_URL: "redis://redis:6379"
  redis:
    image: redis:latest
    ports:
      - "${MOTORHEAD_REDIS_PORT}:6379"
networks:
  default:
    external:
      name: dockgpt-network
