version: "3.9"

services:
  lighthouse:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${LIGHTOUSE_PORT}:80
networks:
  default:
    external:
      name: dockgpt-network
