version: "3.9"

services:
  chroma-server:
    container_name: chroma_server
    build:
      context: ./chroma
      dockerfile: Dockerfile
    volumes:
      - ./chroma:/chroma
      - index_data:/index_data
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config log_config.yml
    environment:
      - CHROMA_DB_IMPL=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    ports:
      - 8002:8000
    depends_on:
      - clickhouse

  clickhouse:
    container_name: chroma_db
    image: clickhouse/clickhouse-server:22.9-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/bitnami/clickhouse
      - backups:/backups
      - ./chroma/config/backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
      - ./chroma/config/chroma_users.xml:/etc/clickhouse-server/users.d/chroma.xml

  motorhead-server:
    container_name: motorhead_server
    build: ./motorhead
    ports:
      - "8081:8080"
    links:
      - motorhead-redis
    environment:
      PORT: 8080
      REDIS_URL: "redis://motorhead-redis:6379"
    env_file:
      - ./motorhead/.env
  motorhead-redis:
    container_name: motorhead_db
    image: redis:latest
    ports:
      - "6379:6379"

  langchain-frontend:
    container_name: langchainplus_front
    image: notlangchain/langchainplus-frontend:latest
    ports:
      - 4173:4173
    environment:
      - BACKEND_URL=http://langchain-backend:8000
      - PUBLIC_BASE_URL=http://localhost:8000
      - PUBLIC_DEV_MODE=true
    depends_on:
      - langchain-backend
  langchain-backend:
    container_name: langchainplus_back
    image: notlangchain/langchainplus:latest
    environment:
      - PORT=8000
      - LANGCHAIN_ENV=local
    ports:
      - 8000:8000
    depends_on:
      - langchain-db
  langchain-db:
    container_name: langchainplus_db
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

volumes:
  clickhouse_data:
    driver: local
  index_data:
    driver: local
  backups:
    driver: local
